Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = Split("""
""")

if GetDepend(['BSP_USING_LED']):
    src += ['drv_led.c']
	


	
path =  [cwd]
group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)

Return('group')