import rtconfig
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, str(Dir('#'))]


src = Glob('*.c')

if GetDepend('APP_USING_CPUUSAGE'):
    src = src + ['extra/cpuusage.c']


group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
